### ISSUE TITLE
Exception when trying to run with --livereload or "ionic serve --engine=cordova --platform=ios"

### ISSUE THREAD

**Issue by sachingarg05** [ionic-team/angular-toolkit#435]
Bug seen in `@ionic/angular-toolkit@2.3.3`
But works OK in `@ionic/angular-toolkit@2.3.0`

Error:
`An unhandled exception occurred: compilation.getLogger is not a function`

With `ionic serve --engine=cordova --platform=ios`
![image](https://user-images.githubusercontent.com/4737179/104112320-6fcb2380-5313-11eb-9ec6-4829e3d9f3b5.png)

With `ionic cordova run android --device --livereload --external`
![image](https://user-images.githubusercontent.com/4737179/104112338-a7d26680-5313-11eb-856a-aed79083efc2.png)

Ionic Info
```
Ionic:

   Ionic CLI                     : 6.12.1 (/Users/user/.npm-global/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 4.11.13
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 9.0.0, ios 6.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, (and 30 other plugins)

Utility:

   cordova-res (update available: 0.15.2) : 0.15.1
   native-run (update available: 1.3.0)   : 1.2.2

System:

   Android SDK Tools : 26.1.1 (/Users/user/Library/Android/sdk)
   ios-deploy        : 1.11.3
   ios-sim           : 8.0.2
   NodeJS            : v12.19.0 (/usr/local/bin/node)
   npm               : 6.13.6
   OS                : macOS Catalina
   Xcode             : Xcode 11.6 Build version 11E708
```

**Comment by mhartington** [comment]
Do you have a sample project we can test against?

**Comment by sachingarg05** [comment]
Error doesn't happen on a fresh Ionic 5 project. My best guess so far is that @ionic/angular-toolkit@2.3.3 isn't compatible with Ionic 4 or with Angular 8. Will share what I find, or prepare a sample project. Couldn't find an easy way to generate a fresh Ionic 4 project.

**Comment by mhartington** [comment]
https://github.com/ionic-team/angular-toolkit/blob/master/CHANGELOG.md#200-2019-06-25

V2 of the toolkit support version 8 of angular. You dont generate *new* v4 project since Ionic uses semantic versioning, so it's all standard changes, not product versions.

**Comment by sachingarg05** [comment]
OK, will test more and report.

**Comment by sachingarg05** [comment]
Planning to test with checkout of (around) 1 year old commit from v4 era of: 
  https://github.com/ionic-team/starters/tree/master/angular/official/blank
or
  https://github.com/ionic-team/starters/tree/master/angular/base

**Comment by mhartington** [comment]
Not sure there's much that we can fix from a release over a year ago. You should be keeping your app's deps up to date.

**Comment by sachingarg05** [comment]
Yes, if the problem is indeed incompatibility with Angular 8, then no point in fixing it now. Will test and confirm. We plan to update to Ionic5+Angular11 soon.

On a side note, what changes in build process by adding `--platform=ios` or `--platform=android` to CLI parameters? Is something different in the generated/compiled code for iOS vs Android? What kind of differences?

Can we do just one build/serve for both iOS and Android using only 
`ionic serve --engine=cordova`

Or do we really need to do separate builds for testing on iOS vs Android using:
```
ionic serve --engine=cordova --platform=ios
ionic serve --engine=cordova --platform=android
```

Same question for 'build':
```
ionic build --engine=cordova --platform=ios --prod
ionic build --engine=cordova --platform=android --prod
```

**Comment by mhartington** [comment]
No, the issue isn't incompatibility.

> `ionic serve --engine=cordova` 

This was never an option, and was never something you could do.

https://ionicframework.com/docs/cli/commands/serve

Not sure where you got the idea that you could do that.

For the `--platform` flags, you can review the builder/source. It's making sure the right plugins for each platform get loaded.


Since is pointing to an _older_ version of angular-toolkit, which we no longer support, I'm going to close this.
